name: "cross-tests"

inputs:
  rust:
    required: true
  package:
    required: true
  target:
    required: true
  features:
    required: true

runs:
  using: "composite"
  steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ inputs.rust }}
          target: ${{ inputs.target }}
          override: true
      - uses: RustCrypto/actions/cross-install@master
      - run: cross test
          --package ${{ inputs.package }}
          --target ${{ inputs.target }}
          --no-default-features
          --features ${{ inputs.features }}
        shell: bash
