name: "cross-tests"

inputs:
  rust:
    required: true
  package:
    required: true
  target:
    required: true
  features:
    required: true

runs:
  using: "composite"
  steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ inputs.rust }}
          target: ${{ inputs.target }}
          override: true
      - name: Install precompiled cross
        run: |
          export URL=$(curl -s https://api.github.com/repos/cross-rs/cross/releases/latest | \
            jq -r '.assets[] | select(.name | contains("x86_64-unknown-linux-gnu.tar.gz")) | .browser_download_url')
          wget -O /tmp/binaries.tar.gz $URL
          tar -C /tmp -xzf /tmp/binaries.tar.gz
          mv /tmp/cross ~/.cargo/bin
        shell: bash
      - run: cross test
          --package ${{ inputs.package }}
          --target ${{ inputs.target }}
          --no-default-features
          --features ${{ inputs.features }}
        shell: bash
