name: Security Audit
on:
  pull_request:
    paths:
      - .github/workflows/security-audit.yml
      - Cargo.lock
  push:
    branches: master
    paths: Cargo.lock
  schedule:
    - cron: "0 0 * * *"

permissions: {}

jobs:
  security_audit:
    name: Security Audit
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: RustCrypto/actions/cargo-cache@master
      - name: Cache cargo bin
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        with:
          path: ~/.cargo/bin
          key: ${{ runner.os }}-cargo-audit-v0.22.0
      - uses: rustsec/audit-check@69366f33c96575abad1ee0dba8212993eecbe998 # v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
